### ISSUE TITLE
functions missing during compilation

### ISSUE THREAD

**Issue by lealoureiro** [strags/pico-rmiieth#1]
Hello!

First of all thank you for sharing the code :)

I'm trying to compile the project out of the box, but I'm facing some problems:

```
/usr/local/Cellar/arm-none-eabi-gcc/9-2019-q4-major/gcc/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: CMakeFiles/rmiieth.dir/Users/leandro/Projects/pico-extras/lib/lwip/src/core/netif.c.obj: in function `netif_do_set_ipaddr':
/Users/leandro/Projects/pico-extras/lib/lwip/src/core/netif.c:491: undefined reference to `acd_netif_ip_addr_changed'
/usr/local/Cellar/arm-none-eabi-gcc/9-2019-q4-major/gcc/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: CMakeFiles/rmiieth.dir/Users/leandro/Projects/pico-extras/lib/lwip/src/core/timeouts.c.obj:(.rodata.lwip_cyclic_timers+0x2c): undefined reference to `acd_tmr'
/usr/local/Cellar/arm-none-eabi-gcc/9-2019-q4-major/gcc/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: CMakeFiles/rmiieth.dir/Users/leandro/Projects/pico-extras/lib/lwip/src/core/ipv4/dhcp.c.obj: in function `dhcp_check':
/Users/leandro/Projects/pico-extras/lib/lwip/src/core/ipv4/dhcp.c:358: undefined reference to `acd_start'
/usr/local/Cellar/arm-none-eabi-gcc/9-2019-q4-major/gcc/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: CMakeFiles/rmiieth.dir/Users/leandro/Projects/pico-extras/lib/lwip/src/core/ipv4/dhcp.c.obj: in function `dhcp_start':
/Users/leandro/Projects/pico-extras/lib/lwip/src/core/ipv4/dhcp.c:806: undefined reference to `acd_add'
/usr/local/Cellar/arm-none-eabi-gcc/9-2019-q4-major/gcc/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: CMakeFiles/rmiieth.dir/Users/leandro/Projects/pico-extras/lib/lwip/src/core/ipv4/etharp.c.obj: in function `etharp_input':
/Users/leandro/Projects/pico-extras/lib/lwip/src/core/ipv4/etharp.c:678: undefined reference to `acd_arp_reply'
collect2: error: ld returned 1 exit status
make[2]: *** [rmiieth.elf] Error 1
make[1]: *** [CMakeFiles/rmiieth.dir/all] Error 2
make: *** [all] Error 2
```

It seems like the file **lwipopts.h** in root of the project is being ignored and lwip is compiled without some functions...

**Comment by strags** [comment]
Hi! Sorry for the delayed response. It looks like the file:

pico-extras/src/rp2_common/lwip/CMakeLists.txt

is missing an entry for:
       ${LWIP_PATH}/src/core/ipv4/acd.c

If you add the above line after:
        ${LWIP_PATH}/src/apps/http/fs.c

It seems to fix things. I'm not sure if this is the right way to fix it, I'll ask on the pico discord when I have a moment. However, the above ought to resolve things for you.


Cheers,
Ben

**Comment by lealoureiro** [comment]
It seems to work now :) Thanks

The only problem now, i can't use the USB serial monitor anymore. The device doest not appear anymore after i uploaded your firmware:

**/dev/cu.usbmodem0000000000001**

I also tried to add the following lines in **CMakeLists.txt** but didn't work either:

```
pico_enable_stdio_usb(rmiieth 1)
pico_enable_stdio_uart(rmiieth 0)
```

**Comment by strags** [comment]
The alternate fix to the original problem is to disable ACD. I've pushed a change to lwipopts.h that fixes this so the project should at least build out-of-the-box with a stock sdk.

I'm not sure about the USB serial - I presume if you want the Pico to act as a CDC serial device there's some code you would need to add at startup in main() - but since I use a USB<->Serial converter I've never dealt with that.
